### ISSUE TITLE
Refactor Simulation Manager and Related Classes

### ISSUE THREAD

**Issue by profbunbun** [profbunbun/SUMO-Routing-RL#11]
## Summary
Refactor the simulation manager and related classes to improve structure and maintainability.

## Tasks
- [ ] Clean up sim manager.
- [ ] Convert sim manager into a class.
- [ ] Combine vehicle and vehicle manager.
- [ ] Consolidate person and manager class.
- [ ] Determine if outmask should be part of a class and incorporate it with the observation class.

## Additional Information
This refactor aims to improve the readability and maintainability of the codebase.
