### ISSUE TITLE
Enhance Passenger and Vehicle Integration

### ISSUE THREAD

**Issue by profbunbun** [profbunbun/SUMO-Routing-RL#12]
## Summary
Improve the integration between passengers and vehicles to better simulate real-world scenarios.

## Tasks
- [ ] Implement passenger entry into vehicles.
- [ ] Add multiple passengers.
- [ ] Add multiple routes.
- [ ] Set this up for multiple taxi stands.
- [ ] Add multiple taxi stands each with a selection of vehicle types.
- [ ] Add more specific regions for generating passenger start and stop points.

## Additional Information
These enhancements will provide a more realistic simulation environment.
