### ISSUE TITLE
Routing comparison 

### ISSUE THREAD

**Issue by profbunbun** [profbunbun/SUMO-Routing-RL#13]
## Summary
Enhance routing algorithms and distance calculation methods.

## Tasks
- [ ] Generate Dijkstra and A* routes for comparison.
- [ ] Determine if this is the best way to get the ideal bus stop.
- [ ] Find a better way to get a route without hardcoding the bus ID.
- [ ] Change the way the vehicle travels from the current teleportation method. 

## Additional Information
Improving these algorithms will help create more efficient and realistic routing.
