### ISSUE TITLE
Organize and Extend RL Models and Networks

### ISSUE THREAD

**Issue by profbunbun** [profbunbun/SUMO-Routing-RL#14]
## Summary
Organize and comment the RL models, and plan to implement additional models and networks.

## Tasks
- [ ] Organize and comment RL models.
- [ ] Create a full list to implement more models like PPO, actor-critic, and others.
- [ ] Implement different networks.

## Additional Information
A well-organized set of models and networks will facilitate experimentation and development.
