### ISSUE TITLE
add-todo's

### ISSUE THREAD

**Issue by profbunbun** [profbunbun/SUMO-Routing-RL#5]
## Summary
We need to add `TODO` comments throughout the codebase to identify areas that need further work or improvements.

### Configurations
- [ ] `configurations/__init__.py`
- [ ] `configurations/config.yaml`

### Environment
- [ ] `environment/__init__.py`
- [ ] `environment/bus_stop.py`
- [ ] `environment/env.py`
- [ ] `environment/observation.py`
- [ ] `environment/outmask.py`
- [ ] `environment/person.py`
- [ ] `environment/person_manager.py`
- [ ] `environment/reward.py`
- [ ] `environment/ride_select.py`
- [ ] `environment/sim_manager.py`
- [ ] `environment/vehicle.py`
- [ ] `environment/vehicle_manager.py`

#### DQN
- [ ] `rl_algorithms/dqn/__init__.py`
- [ ] `rl_algorithms/dqn/agent.py`
- [ ] `rl_algorithms/dqn/peragent.py`
#### Exploration
- [ ] `rl_algorithms/exploration/__init__.py`
- [ ] `rl_algorithms/exploration/exploration.py`
#### Memory Buffers
- [ ] `rl_algorithms/memory_buffers/__init__.py`
- [ ] `rl_algorithms/memory_buffers/permem.py`
- [ ] `rl_algorithms/memory_buffers/ppobuff.py`
- [ ] `rl_algorithms/memory_buffers/replay_memory.py`
#### Models
- [ ] `rl_algorithms/models/__init__.py`
- [ ] `rl_algorithms/models/dqn.py`
- [ ] `rl_algorithms/models/ppon.py`
#### PPO
- [ ] `rl_algorithms/ppo/__init__.py`
- [ ] `rl_algorithms/ppo/ppoagent.py`
- [ ] `rl_algorithms/__init__.py`

### Utils
- [ ] `utils/__init__.py`
- [ ] `utils/connect.py`
- [ ] `utils/net_parser.py`
- [ ] `utils/utils.py`

### Main
- [ ] `__init__.py`
- [ ] `main.py`

## Expected Outcome
A clear and documented codebase with `TODO` comments indicating areas for future work.
